// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddReaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddReaction'](arg1, arg2, arg3, arg4);
}

export function CheckAuth(arg1) {
  return window['go']['main']['App']['CheckAuth'](arg1);
}

export function CreateChannel(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChannel'](arg1, arg2, arg3);
}

export function DeleteChannel(arg1, arg2) {
  return window['go']['main']['App']['DeleteChannel'](arg1, arg2);
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function JoinChannel(arg1, arg2) {
  return window['go']['main']['App']['JoinChannel'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendPost(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPost'](arg1, arg2, arg3);
}

export function UpdateUserStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserStatus'](arg1, arg2);
}
