// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddReaction(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CheckAuth(arg1:string):Promise<string>;

export function CreateChannel(arg1:string,arg2:string,arg3:string):Promise<main.Channel>;

export function DeleteChannel(arg1:string,arg2:string):Promise<void>;

export function DeleteDMChannel(arg1:string,arg2:string):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Message>;

export function GetChannels():Promise<Array<main.Channel>>;

export function GetDMChannels(arg1:string):Promise<Array<main.Channel>>;

export function GetFileData(arg1:string):Promise<string>;

export function GetMessages(arg1:string):Promise<Array<main.Message>>;

export function GetOrCreateDMChannel(arg1:string,arg2:string):Promise<main.Channel>;

export function GetUnreadCounts(arg1:string):Promise<Record<string, number>>;

export function GetUsers():Promise<Array<main.User>>;

export function JoinChannel(arg1:string,arg2:string):Promise<void>;

export function LogCall(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.Message>;

export function Login(arg1:string,arg2:string):Promise<main.User>;

export function Logout(arg1:string):Promise<boolean>;

export function MarkChannelRead(arg1:string,arg2:string):Promise<void>;

export function Register(arg1:string,arg2:string):Promise<main.User>;

export function SaveFileToDisk(arg1:string):Promise<void>;

export function SearchMessages(arg1:string,arg2:string):Promise<Array<main.Message>>;

export function SendFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Message>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendPost(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateUserStatus(arg1:string,arg2:string):Promise<boolean>;
